Docker 3
Otus-DevOps-2023-03/malkops_microservices pull request #2
Opened 2023-06-13 07:46 UTC by malkops

# Выполнено ДЗ № 14

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Скачаны исходные коды приложения
 - Созданы докерфайлы для этого приложения

## Как запустить проект:
 - Поднять 3 контейнера исходников и БД

## Как проверить работоспособность:
 - Проверить доступность по http://localhost:9292

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2023-06-13 07:54 UTC, malkops commented
Не понятно, почему тесты не прошли, так как описание и рабочие докерфайлы есть

2023-06-13 14:37 UTC, mrgreyves requested changes
Здравствуйте!)
Вам просто нужно добавить пустые строки в конец докерфайлов
Это быстро

2023-06-14 05:05 UTC, malkops commented
Теперь непонятно почему не собирается в тесте
![image](https://github.com/Otus-DevOps-2023-03/malkops_microservices/assets/44001733/46726f94-d169-440f-bceb-f1b56a789f6a)

2023-06-25 13:18 UTC, mrgreyves approved these changes
Здравствуйте!)
Похоже на какую то временную историю

2023-06-26 05:08 UTC, merged